---
name: otlplus
description: Online Timeplanner with Lectures Plus App @ KAIST
version: 2.5.19+260604
environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"
publish_to: none
dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: "^9.2.2"
  app_links: "^6.1.1"
  dio: "^5.7.0"
  dotted_border: "^2.1.0"
  flutter_web_browser: "^0.17.3"
  webview_flutter: "^4.14.1"
  path_provider: "^2.1.6"
  permission_handler: "^11.3.1"
  provider: "^6.1.2"
  url_launcher: "^6.3.1"
  equatable: "^2.0.7"
  shared_preferences: "^2.5.5"
  easy_localization: "^3.0.7"
  flutter_widgetkit: "^1.0.3"
  flutter_svg: "^2.3.0"
  open_app_file: "^4.0.2"
  flutter_native_splash: "^2.4.8"
  mailto: "^2.0.0"
  dropdown_button2: "^3.0.0-beta.21"
  firebase_core: "^3.10.0"
  firebase_analytics: "^11.4.0"
  firebase_crashlytics: "^4.3.0"
  firebase_messaging: "^15.2.0"
  channel_talk_flutter:
    git:
      url: https://github.com/happycastle114/channel_talk_flutter
      ref: main
  in_app_update: ^4.2.5
  sentry_flutter: ^9.27.0
  posthog_flutter: ^5.35.1
dev_dependencies:
  sentry_dart_plugin: ^3.1.2
  test: "^1.25.7"
  http: "^1.2.2"
  cookie_jar: "^4.0.8"
  dio_cookie_manager: "^3.1.1"
  html: "^0.15.4"
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
flutter_icons:
  android: true
  ios: true
  image_path: assets/icons/icon-512.png
  adaptive_icon_background: "#F9F0F0"
  adaptive_icon_foreground: assets/icons/icon-512-foreground.png
flutter:
  uses-material-design: true
  assets:
  - assets/
  - assets/people/
  - assets/images/
  - assets/translations/
  - assets/icons/
  - assets/popups/
  fonts:
  - family: NotoSansKR
    fonts:
    - asset: assets/fonts/NotoSansKR-Thin.otf
      weight: 100
    - asset: assets/fonts/NotoSansKR-Light.otf
      weight: 300
    - asset: assets/fonts/NotoSansKR-Regular.otf
      weight: 400
    - asset: assets/fonts/NotoSansKR-Medium.otf
      weight: 500
    - asset: assets/fonts/NotoSansKR-Bold.otf
      weight: 700
    - asset: assets/fonts/NotoSansKR-Black.otf
      weight: 900
  - family: Raleway
    fonts:
    - asset: assets/fonts/Raleway-Thin.ttf
      weight: 100
    - asset: assets/fonts/Raleway-Light.ttf
      weight: 300
    - asset: assets/fonts/Raleway-Regular.ttf
      weight: 400
    - asset: assets/fonts/Raleway-Medium.ttf
      weight: 500
    - asset: assets/fonts/Raleway-Bold.ttf
      weight: 700
    - asset: assets/fonts/Raleway-ExtraBold.ttf
      weight: 800
    - asset: assets/fonts/Raleway-Black.ttf
      weight: 900
  - family: NanumSquare
    fonts:
    - asset: assets/fonts/NanumSquareL.otf
      weight: 300
    - asset: assets/fonts/NanumSquareR.otf
      weight: 400
    - asset: assets/fonts/NanumSquareB.otf
      weight: 700
    - asset: assets/fonts/NanumSquareEB.otf
      weight: 800

sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  upload_sources: true
  project: "otl-app"
  org: "sentry"
  url: "https://sentry.sparcs.org"
