# Removed update_fastlane to avoid Bundler gem version conflicts in CI
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Set timestamp version from pubspec.yaml"
  lane :set_timestamp_version do
      yaml_file_path = "../../pubspec.yaml"
      data = YAML.load_file(yaml_file_path)
      version = data["version"]

      version_number = data["version"].split("+")[0]
      version_code = Time.now.strftime("%y%m%d%H%M").to_i - 2100000000
      new_version = "#{version_number}+#{version_code}"

      data["version"] = new_version
      File.open(yaml_file_path, 'w') { |f| YAML.dump(data, f) }
  end

  desc "Deploy a alpha version to the Google Play"
  lane :alpha do
    set_timestamp_version
    posthog_host = ENV.fetch("POSTHOG_HOST", "https://us.i.posthog.com")
    sh "flutter build appbundle --dart-define=POSTHOG_API_KEY=#{ENV.fetch('POSTHOG_API_KEY')} --dart-define=POSTHOG_HOST=#{posthog_host}"
    upload_to_play_store(
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      track: "alpha",
    )
  end

  desc "Submit a staged production release for Google Play review"
  lane :production_review do
    set_timestamp_version
    posthog_host = ENV.fetch("POSTHOG_HOST", "https://us.i.posthog.com")
    sh "flutter build appbundle --dart-define=POSTHOG_API_KEY=#{ENV.fetch('POSTHOG_API_KEY')} --dart-define=POSTHOG_HOST=#{posthog_host}"
    upload_to_play_store(
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      track: "production",
      rollout: "0.1",
      release_status: "inProgress",
    )
  end
end
